AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura

Resources:

  Keyspace:
    Type: AWS::Cassandra::Keyspace
    Properties:
      KeyspaceName: !Sub '${ProjectName}_simple2'

  SimpleTable:
    Type: AWS::Cassandra::Table
    Properties:
      TableName: notifications
      KeyspaceName: !Ref Keyspace
      PartitionKeyColumns:
        - ColumnName: pk
          ColumnType: text
      RegularColumns:
        - ColumnName: value
          ColumnType: text

  DocumentBucket:
    Type: AWS::S3::Bucket

Outputs:
  KeyspaceName:
    Description: Keyspace Name used by application to access the key-value store
    Value: !Ref Keyspace

  DocumentBucketName:
    Description: name of bucket going to contains notification documents
    Value: !Ref DocumentBucket

  DocumentsBucketArn:
    Description: ARN of bucket going to contains notification documents
    Value: !Sub '${DocumentBucket.Arn}'


